
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC
org.gradle.parallel=true

org.gradle.caching=true

android.useAndroidX=true
# We don't use dependencies relying on legacy Android support libraries, so no need for jetifier.
android.enableJetifier=false

android.nonTransitiveRClass=true

android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.shaders=false

# platform activation
include_android=true
include_js=true
include_jfx=true
include_ios=false
include_jfx_renderings=false

coroutines_version = 1.6.4
geojson_version=0.6.6
kotlinx_datetime_version=0.4.0

textfx_version=4.0.4-alpha

group=io.data2viz
#org.gradle.configureondemand=false

kotlin.code.style=official
kotlin.incremental.multiplatform=true
kotlin.incremental.js=true
kotlin.mpp.enableGranularSourceSetsMetadata=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.stability.nowarn=true
kotlin.js.compiler=both
kotlin.native.ignoreDisabledTargets=true
kotlin.native.cacheKind.iosArm64=none
kotlin.native.enableDependencyPropagation=false

dryRun = false
