

if (include_android.toBoolean()) {
    apply plugin: 'com.android.kotlin.multiplatform.library'
    kotlin {
        android {
            // e.g. d2v-axis -> io.data2viz.axis
            namespace = "io.data2viz.${project.name.replace('d2v-', '').replace('-', '.')}"
            compileSdk = 36
            minSdk = 17
        }
        sourceSets {
            androidMain {
            }
            androidUnitTest {
                dependencies {
                    implementation project(":d2v-tests")
                    implementation kotlin('test-junit')
                }
            }
        }
    }

}

