
apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'maven-publish'

kotlin {

    abiValidation {
        enabled = true
        filters {
            excluded {
                annotatedWith.add("io.data2viz.ExperimentalD2V")
                annotatedWith.add("io.data2viz.InternalAPI")
            }
        }
    }

    explicitApiWarning()

    metadata {
    }

    sourceSets {
        commonMain {
        }
        commonTest {
            dependencies {
                if (project.name != "tests") {
                    implementation project(":d2v-tests")
                }
                implementation kotlin('test')
            }
        }
    }
}


