

if (include_jfx.toBoolean() || include_android.toBoolean()) {
    kotlin {
        jvm {
            compilations.all {
                kotlinOptions {
                    jvmTarget = '1.8'
                }
            }
        }
        sourceSets {

            jvmMain {
            }
            jvmTest {
                dependencies {
                    if (project.name != "tests") {
                        implementation project(":d2v-tests")
                    }
                    implementation kotlin('test-junit')
                }
            }

        }

    }

}
