

if (include_ios.toBoolean()) {

    kotlin {

        iosArm64 {
            binaries {
                framework {
                    baseName = "d2v-$project.name"
                }
            }
        }
        iosX64 {
            binaries {
                framework {
                    baseName = "d2v-$project.name"
                }
            }
        }
        iosSimulatorArm64 {
            binaries {
                framework {
                    baseName = "d2v-$project.name"
                }
            }
        }

        applyDefaultHierarchyTemplate()

        targets.matching { it.name.startsWith('ios') }.configureEach {
            compilations.configureEach {
                kotlinOptions {
                    freeCompilerArgs += ['-opt-in=kotlinx.cinterop.ExperimentalForeignApi']
                }
            }
        }

        sourceSets {
            iosTest {
                dependencies {
                    if (project.name != "tests") {
                        implementation project(":d2v-tests")
                    }
                }
            }
        }
    }

}

