# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Run Gradle check
on:
  workflow_dispatch:
  push:
    paths:
      - '!CHANGELOG.md'
      - '!README.md'
      - '!libraries_version.txt'
jobs:
  linux-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run check on Linux
        run: >-
          ./gradlew --console=plain
          check
  macos-check:
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run check on macOS
        run: >-
          ./gradlew --console=plain
          check
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -Dfile.encoding=UTF-8"
