name: MPP iOS build

on: [push]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: "Configure JDK"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew check -Pinclude_ios=true -Pinclude_android=false -Pinclude_js=false -Pinclude_jfx=false
