name: MPP JavaFx build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          java-package: jdk+fx # (jre, jdk, or jdk+fx)

      - name: Build with Gradle
        run: ./gradlew check -Pinclude_ios=false -Pinclude_android=false -Pinclude_js=false -Pinclude_jfx=true
