name: MPP Android build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Configure JDK"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew check -Pinclude_ios=false -Pinclude_android=true -Pinclude_js=false -Pinclude_jfx=false
