# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Publish to Sonatype Snapshots
on:
  workflow_dispatch:
jobs:
  linux-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Upload all artifacts Linux can build
        run: >-
          ./gradlew --console=plain
          publishAllPublicationsToSonatypeSnapshotsRepository
  macos-upload:
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Upload Darwin artifacts
        run: >-
          ./gradlew --console=plain
          publishIosArm64PublicationToSonatypeSnapshotsRepository
          publishIosX64PublicationToSonatypeSnapshotsRepository
          publishIosSimulatorArm64PublicationToSonatypeSnapshotsRepository
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -Dfile.encoding=UTF-8"
  sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
  sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_key_id: ${{ secrets.GPG_KEY_ID }}
  GPG_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_private_password: ${{ secrets.GPG_PRIVATE_PASSWORD }}
